(* ::Package:: *)

(************************************************************************)
(* This file was generated automatically by the Mathematica front end.  *)
(* It contains Initialization cells from a Notebook file, which         *)
(* typically will have the same name as this file except ending in      *)
(* ".nb" instead of ".m".                                               *)
(*                                                                      *)
(* This file is intended to be loaded into the Mathematica kernel using *)
(* the package loading commands Get or Needs.  Doing so is equivalent   *)
(* to using the Evaluate Initialization Cells menu command in the front *)
(* end.                                                                 *)
(*                                                                      *)
(* DO NOT EDIT THIS FILE.  This entire file is regenerated              *)
(* automatically each time the parent Notebook file is saved in the     *)
(* Mathematica front end.  Any changes you make to this file will be    *)
(* overwritten.                                                         *)
(************************************************************************)



(* ::Input::Initialization:: *)
initialList={LABColor[0.5187848173343539, 0.6399990176455989, 0.67],LABColor[0.8300000000000001, 0.04, 0.8],LABColor[0.7034977311779242, -0.6348740400535063, 0.62490305423001],LABColor[0.794283848056134, -0.3547323340157605, -0.31862459565533907`],LABColor[0.4417864340686453, 0.40076871833601263`, -0.8768750645112572],LABColor[0.6263977928344144, 0.8658104149752872, -0.565775642691356]};


(* ::Input::Initialization:: *)
periodicList=Join[initialList,{initialList[[1]]}];


(* ::Input::Initialization:: *)
interpolationPoints=100;


(* ::Input::Initialization:: *)
colorDifference[{L1_,a1_,b1_},{L2_,a2_,b2_}]:=ColorDistance[LABColor[L1,a1,b1],LABColor[L2,a2,b2],DistanceFunction->"CIE2000"];


(* ::Input::Initialization:: *)
ListPlot[
accumulatedDifferences=Accumulate[
Map[
Apply[colorDifference[#1,#2]&],
Partition[
Table[
Interpolation[
Transpose[{
Range[0,1,1/(Length[periodicList]-1)],
List@@@(ColorConvert[#,"LAB"]&/@periodicList)
}]
,InterpolationOrder->1
][x]
,{x,0,1,1/interpolationPoints}]
,2,1]
]
]
,Frame->True
,AspectRatio->1
]


(* ::Input::Initialization:: *)
colorList=Table[
{y,
Interpolation[
Transpose[{
Range[0,1,1/(Length[periodicList]-1)],
List@@@(ColorConvert[#,"LAB"]&/@periodicList)
}]
,InterpolationOrder->1
][
Interpolation[
Reverse/@Transpose[{
Range[0,1,1/interpolationPoints],
Join[{0},accumulatedDifferences]/Last[accumulatedDifferences]
}]
][y]
]
}
,{y,0,1,1/interpolationPoints}];


(* ::Input::Initialization:: *)
PUCCS[x_]=Blend[
Table[
{x,
ColorConvert[
LABColor@@Interpolation[
colorList
,InterpolationOrder->1
][x]
,"RGB"]
}
,{x,0,1,0.01}]
,x]


(* ::Input::Initialization:: *)
strip=DensityPlot[
x,{x,0,6},{y,0,1}
,ColorFunction->PUCCS
,PlotRangePadding->None
,AspectRatio->1/8
,ImageSize->600
]


(* ::Input::Initialization:: *)
KovesiWashboardF[x_,y_,f_:50.5,a_:0.05]:=x-a y^2 (2x-2 0.5)-y^2 a Cos[f 2\[Pi] x]


(* ::Input::Initialization:: *)
washboard=DensityPlot[
KovesiWashboardF[x/6,y,80.5,0.05]
,{x,0,6},{y,0,1}
,AspectRatio->1/2.5
,PlotRangePadding->None
,ImageSize->700
,PlotPoints->200
,ColorFunction->PUCCS
]


(* ::Input::Initialization:: *)
circle=Show[{
DensityPlot[
Arg[(x+I y)]
,{x,-1,1},{y,-1,1}
,ColorFunction->Function[PUCCS[1/(2\[Pi]) Mod[#,2\[Pi]]]]
,ColorFunctionScaling->False
,ExclusionsStyle->PUCCS[0.5]
,RegionFunction->Function[{x,y,f},0.5^2<=x^2+y^2<=1]
,Frame->False
],
Graphics[{
Circle[{0,0},1],
Circle[{0,0},0.5]
}],
Graphics[{
Table[
Text[\[Theta],1.05{Cos[\[Theta]],Sin[\[Theta]]}]
,{\[Theta],0,359\[Degree],30\[Degree]}]
}],
Graphics[{}]
}
,ImageSize->400
,PlotRange->All
]


(* ::Input::Initialization:: *)
LGdonut=RegionPlot[
True
,{x,-3,3},{y,-3,3}
,ColorFunction->Function[{x,y},Directive[
Blend[{White,PUCCS[1/2+1/(2\[Pi]) Arg[(x+I y)^2]]},Abs[1/E^-1 (x+I y)^2 Exp[-(x^2+y^2)]]]
]]
,ColorFunctionScaling->False
,PlotRangePadding->None
,PlotPoints->150
,ImageSize->450
]



